### ISSUE TITLE
Build break

### ISSUE THREAD

**Issue by hkim15** [jeehoonkang/hafnium#6]
I followed the instructions in hfo2/README.md. 

cargo xbuild --manifest-path hfo2/Cargo.toml --target hfo2/aarch64-hfo2.json --release
    Finished release [optimized] target(s) in 0.02s
cargo xbuild --manifest-path hfo2/Cargo.toml --target hfo2/aarch64-hfo2-test.json --features "test" --release
    Finished release [optimized] target(s) in 0.02s
cargo build --manifest-path hfo2/Cargo.toml --release
    Finished release [optimized] target(s) in 0.02s
make: $HOME/temp/hafnium/prebuilts/linux-x64/gn/gn: Command not found
Makefile:48: recipe for target 'out/reference/build.ninja' failed
make: *** [out/reference/build.ninja] Error 127

**Comment by jeehoonkang** [comment]
It seems you didn't download git submodule dependencies.  Please follow the instruction here: https://github.com/jeehoonkang/hafnium/blob/hfo2/docs/GettingStarted.md

**Comment by hkim15** [comment]
Thanks. That fixed the issue. I am curious how C & Rust code inter-operates. I am expecting that I'd be able to figure it out as I learn more about Rust.
